apiVersion: v1
kind: Pod
metadata:
  name: batman-gpu
  namespace: chrs
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 2
        memory: "20Gi"
      requests:
        memory: "20Gi"
        volumeMounts:
    - mountPath: /batman-vol
      name: batman-vol
  restartPolicy: Never
  volumes:
    - name: batman-vol
      persistentVolumeClaim:
        claimName: batman-vol
