apiVersion: v1
kind: Pod
metadata:
  name: batman-gpu
  namespace: chrs
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest # bc47da8c
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: "8Gi"
      requests:
        memory: "8Gi"
    volumeMounts:
      - mountPath: /batman-vol
        name: batman-vol
  restartPolicy: Never
  volumes:
    - name: batman-vol
      persistentVolumeClaim:
        claimName: batman-vol
  securityContext:
    fsGroup: 100


# gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:bc47da8c
