apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Batman_Vol
  namespace: chrs
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
