apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: pace-ucicl
spec:
  containers:
  - name: cpu-demo-ctr
    image: busybox #gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:9108e5a2
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
