apiVersion: v1
kind: Pod
metadata:
  name: abbas-gpu-node
  namespace: chrs
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 4
        memory: "100Gi"
        cpu: "4000m"